## Launch Tayga to perform NAT64 in a container

# Default environment variables
TAYGA_POOL4="${TAYGA_POOL4:-192.168.255.0/24}"
TAYGA_POOL6="${TAYGA_POOL6:-64:ff9b::/96}"
TAYGA_ADDR4="${TAYGA_ADDR4:-192.168.255.1}"
TAYGA_WKPF_STRICT="${TAYGA_WKPF_STRICT:-no}"

if [[ -z "${TAYGA_ADDR6}" ]]; then
    IP6ADDR=""
else
    IP6ADDR="ipv6-addr ${TAYGA_ADDR6}"
fi

# Generate tayga.conf file
cat << EOF > /app/tayga.conf.gen
# tayga.conf
# This file is generated by launch-nat64.sh

tun-device nat64
ipv4-addr ${TAYGA_ADDR4}
prefix ${TAYGA_POOL6}
dynamic-pool ${TAYGA_POOL4}
${IP6ADDR}
data-dir /var/tayga
wkpf-strict ${TAYGA_WKPF_STRICT}
EOF

# If tayga.conf does not already exist, use our new conf
if test -f /app/tayga.conf; then
    echo "tayga.conf already exists, not overwriting"
else
    echo "tayga.conf does not exist, creating it"
    mv /app/tayga.conf.gen /app/tayga.conf
fi

# Make tunnel adapter
echo "Creating tunnel adapter"
/app/tayga -c /app/tayga.conf -d --mktun

# Bring up the interface
echo "Bringing up the interface"
ip link set dev nat64 up
ip addr add ${TAYGA_POOL4} dev nat64
ip addr add ${TAYGA_POOL6} dev nat64

# Enable Forwarding
echo "Enabling IPv4 and IPv6 forwarding"
echo 1 > /proc/sys/net/ipv4/conf/all/forwarding
echo 1 > /proc/sys/net/ipv6/conf/all/forwarding

# Start tayga
echo "Starting tayga"
/app/tayga -c /app/tayga.conf -d