## Launch Tayga to perform NAT64 in a container

# Default environment variables
TAYGA_POOL4="${TAYGA_POOL4:-192.168.255.0/24}"
TAYGA_POOL6="${TAYGA_POOL6:-64:ff9b::/96}"
TAYGA_WKPF_STRICT="${TAYGA_WKPF_STRICT:-no}"

# Auto-detect ADDR4 and ADDR6 from the container if not set
if [[ -z "${TAYGA_ADDR4}" ]]; then
    ADDR4=$(ip addr show eth0 | grep -E 'inet ' | awk '{print $2}' | cut -d'/' -f1 | head -n 1)
    if [[ -z "${ADDR4}" ]]; then
        echo "No IPv4 address found on iface eth0, exiting"
        exit 1
    fi
    TAYGA_ADDR4="${ADDR4}"
    echo Using Container Addr4 $TAYGA_ADDR4
fi

if [[ -z "${TAYGA_ADDR6}" ]]; then
    ADDR6=$(ip addr show eth0 | grep -E 'inet6 ' | awk '{print $2}' | cut -d'/' -f1 | head -n 1)
    if [[ -z "${ADDR6}" ]]; then
        echo "No IPv6 address found, exiting"
        exit 1
    fi
    TAYGA_ADDR6="${ADDR6}"
    echo Using Container Addr6 $TAYGA_ADDR6
fi

# Generate tayga.conf file
cat << EOF > /app/tayga.conf.gen
# tayga.conf
# This file is generated by launch-nat64.sh

tun-device nat64
ipv4-addr ${TAYGA_ADDR4}
prefix ${TAYGA_POOL6}
dynamic-pool ${TAYGA_POOL4}
ipv6-addr ${TAYGA_ADDR6}
data-dir /var/tayga
wkpf-strict ${TAYGA_WKPF_STRICT}
EOF

# If tayga.conf does not already exist, use our new conf
if test -f /app/tayga.conf; then
    echo "tayga.conf already exists, not overwriting"
else
    echo "tayga.conf does not exist, creating it from environment variables"
    mv /app/tayga.conf.gen /app/tayga.conf
fi

# Make tunnel adapter
echo "Creating tunnel adapter"
/app/tayga -c /app/tayga.conf -d --mktun || exit 1

# Bring up the interface
echo "Bringing up the interface"
ip link set dev nat64 up
ip addr add ${TAYGA_POOL4} dev nat64
ip addr add ${TAYGA_POOL6} dev nat64

# Enable Forwarding
echo "Enabling IPv4 and IPv6 forwarding"
echo 1 > /proc/sys/net/ipv4/conf/all/forwarding
echo 1 > /proc/sys/net/ipv6/conf/all/forwarding

# Start tayga
echo "Starting tayga"
/app/tayga -c /app/tayga.conf -d

# Delete tunnel adapter on exit
echo "Deleting tunnel adapter on exit"
ip link del nat64