# This is a basic workflow that is manually triggered

name: Run Test Suite

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    test:
        runs-on: ubuntu-latest  
        steps:
          - uses: actions/checkout@v4
            with:
                fetch-depth: 0
          - name: run build
            run: make
          - name: install deps
            run: sudo apt-get install -y python3-pyroute2 python3-scapy
          - name: run test
            run: sudo test/fullsuite.sh
          - uses: actions/upload-artifact@v4
            with:
                name: results
                path: |
                    test/*.rpt
                    test/*.log
                if-no-files-found: error
